#####################
### truckwregister ###
#####################

# base image
FROM nginx:alpine

# copy artifact build from the 'build environment'
COPY ./dist/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx.conf /etc/nginx/conf.d
# expose port 40
EXPOSE 44

# run nginx
CMD ["nginx", "-g", "daemon off;"]

# npm run build
# docker build -t truckwregister -f Dockerfile-build-app .
# docker run -itd -p 4044:44 truckwregister

#docker run -itd -p 4044:44 --name truckwregister truckwregister


#docker save -o D:\KI\Vuejs\PROJECT\build\truckwregister_frontend.tar truckwregister
#docker load -i D:\Inbox\truckwregister_frontend.tar

